name: esercizi
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/riunito.jpg
    - assets/iconahome.png
    - assets/incisivo-sup-dx.png
    - assets/incisivo-lat-sup-dx.png
    - assets/canino-sup-dx.png
    - assets/incisivo-sup-dx.png
    - assets/primo-premolare-sup-dx.png
    - assets/secondo-premolare-sup-dx.png
    - assets/primo-molare-sup-dx.png
    - assets/secondo-molare-sup-dx.png
    - assets/terzo-molare-sup-dx.png
    - assets/incisivo-sup-sx.png
    - assets/incisivo-lat-sup-sx.png
    - assets/canino-sup-sx.png
    - assets/incisivo-sup-sx.png
    - assets/primo-premolare-sup-sx.png
    - assets/secondo-premolare-sup-sx.png
    - assets/primo-molare-sup-sx.png
    - assets/secondo-molare-sup-sx.png
    - assets/terzo-molare-sup-sx.png
    - assets/riunito.jpg
    - assets/incisivo-inf-dx.png
    - assets/incisivo-lat-inf-dx.png
    - assets/canino-inf-dx.png
    - assets/incisivo-inf-dx.png
    - assets/primo-premolare-inf-dx.png
    - assets/secondo-premolare-inf-dx.png
    - assets/primo-molare-inf-dx.png
    - assets/secondo-molare-inf-dx.png
    - assets/terzo-molare-inf-dx.png
    - assets/incisivo-inf-sx.png
    - assets/incisivo-lat-inf-sx.png
    - assets/canino-inf-sx.png
    - assets/incisivo-inf-sx.png
    - assets/primo-premolare-inf-sx.png
    - assets/secondo-premolare-inf-sx.png
    - assets/primo-molare-inf-sx.png
    - assets/secondo-molare-inf-sx.png
    - assets/terzo-molare-inf-sx.png